name: Performance benchmarking

# `workflow_dispatch` allows CodSpeed to trigger backtest
# performance analysis in order to generate initial data.
on: [push, pull_request, workflow_dispatch]

jobs:
  codspeed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: tools/ci.sh unix_standard_build
    - name: Run the benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        mode: simulation
        run: cd tests && ./run-perfbench.py --average 10 1000 1000
